---
- name: Install some basic packages defined in variable "packages"
  yum:
    name: '{{ item }}'
    state: present
  loop: '{{ packages }}'

- name: Enable Nginx service, ensure it is not masked and start it
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    masked: no

- name: Create "{{ app_dir }}" directory if it does not exist
  become: true
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0755'

- name: Download Java app to {{ app_dir }}/{{ app_file }}
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/devops-practice-files/systemd/ServicesLab-0.0.1.jar
    dest: "{{ app_dir }}/{{ app_file }}"
    owner: "{{ ansible_user_id }}"
    mode: '0644'
  environment:
    https_proxy: 'http://user:password@sgproxy.proxy.com:3128'
    
- name: Create a Java App Unit
  ansible.builtin.template:
    src: templates/app.service.j2
    dest: /etc/systemd/system/sample.service
    mode: '0644'
    owner: root
    group: root

- name: Enable sample.service, ensure it is not masked and start it
  become: true
  ansible.builtin.systemd:
    name: sample.service
    enabled: yes
    masked: no
    state: started

- name: Create a Nginx config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root

- name: Reload Systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Nginx
  become: true
  ansible.builtin.systemd:
    name: sample.service
    state: restarted

